logging:
  level: INFO
  loggers:
    nl.ajax.alert: DEBUG
database:
  driverClass: org.h2.Driver
  url: jdbc:h2:mem:matchdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  user: sa
  password: ""
  validationQuery: "SELECT 1"
  minSize: 2
  maxSize: 10
  properties:
    hibernate.hbm2ddl.auto: update
twilioAccountSid: ${TWILIO_ACCOUNT_SID}
twilioAuthToken: ${TWILIO_AUTH_TOKEN}
