database:
  driverClass: org.h2.Driver
  url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;
  user: sa
  password: ""
  validationQuery: "SELECT 1"
  minSize: 2
  maxSize: 10
  properties:
    hibernate.hbm2ddl.auto: update